files:
  - source: /kartonche/Resources/Localizable.xcstrings
    translation: /kartonche/Resources/Localizable.xcstrings
    type: string_catalog
    multilingual: 1
    update_option: update_as_unapproved
